/*
 * This file is part of the ZoRa project: http://www.photozora.org.
 *
 * ZoRa is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * ZoRa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ZoRa; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * (c) 2012 Berthold Daum  
 */
package com.bdaum.zoom.core.internal;

import java.util.HashMap;
import java.util.Map;

import com.bdaum.zoom.common.GeoMessages;

@SuppressWarnings("nls")
public class LocationConstants {

	public static final String ANTARCTICA = "AN"; //$NON-NLS-1$
	public static final String SOUTH_AMERICA = "SA"; //$NON-NLS-1$
	public static final String NORTH_AMERICA = "NA"; //$NON-NLS-1$
	public static final String OCEANIA = "OC"; //$NON-NLS-1$
	public static final String AFRICA = "AF"; //$NON-NLS-1$
	public static final String EUROPE = "EU"; //$NON-NLS-1$
	public static final String ASIA = "AS"; //$NON-NLS-1$

	public static final String[][] COUNTRIES = new String[][] {
			// `code`,
			// `continent_code`,
			// `name`,
			// `iso3`,
			// `number`,
			// `full_name`
			new String[] { AFRICA, ASIA, "Afghanistan", "AFG", "004",
					"Islamic Republic of Afghanistan" },
			new String[] { "AX", EUROPE, "Åland Islands", "ALA", "248",
					"Åland Islands" },
			new String[] { "AL", EUROPE, "Albania", "ALB", "008",
					"Republic of Albania" },
			new String[] { "DZ", AFRICA, "Algeria", "DZA", "012",
					"People's Democratic Republic of Algeria" },
			new String[] { ASIA, OCEANIA, "American Samoa", "ASM", "016",
					"American Samoa" },
			new String[] { "AD", EUROPE, "Andorra", "AND", "020",
					"Principality of Andorra" },
			new String[] { "AO", AFRICA, "Angola", "AGO", "024",
					"Republic of Angola" },
			new String[] { "AI", NORTH_AMERICA, "Anguilla", "AIA", "660",
					"Anguilla" },
			new String[] { "AQ", ANTARCTICA, "Antarctica", "ATA", "010",
					"Antarctica new String[] {the territory South of 60 deg S}" },
			new String[] { "AG", NORTH_AMERICA, "Antigua and Barbuda", "ATG",
					"028", "Antigua and Barbuda" },
			new String[] { "AR", SOUTH_AMERICA, "Argentina", "ARG", "032",
					"Argentine Republic" },
			new String[] { "AM", ASIA, "Armenia", "ARM", "051",
					"Republic of Armenia" },
			new String[] { "AW", NORTH_AMERICA, "Aruba", "ABW", "533", "Aruba" },
			new String[] { "AU", OCEANIA, "Australia", "AUS", "036",
					"Commonwealth of Australia" },
			new String[] { "AT", EUROPE, "Austria", "AUT", "040",
					"Republic of Austria" },
			new String[] { "AZ", ASIA, "Azerbaijan", "AZE", "031",
					"Republic of Azerbaijan" },
			new String[] { "BS", NORTH_AMERICA, "Bahamas", "BHS", "044",
					"Commonwealth of the Bahamas" },
			new String[] { "BH", ASIA, "Bahrain", "BHR", "048",
					"Kingdom of Bahrain" },
			new String[] { "BD", ASIA, "Bangladesh", "BGD", "050",
					"People's Republic of Bangladesh" },
			new String[] { "BB", NORTH_AMERICA, "Barbados", "BRB", "052",
					"Barbados" },
			new String[] { "BY", EUROPE, "Belarus", "BLR", "112",
					"Republic of Belarus" },
			new String[] { "BE", EUROPE, "Belgium", "BEL", "056",
					"Kingdom of Belgium" },
			new String[] { "BZ", NORTH_AMERICA, "Belize", "BLZ", "084",
					"Belize" },
			new String[] { "BJ", AFRICA, "Benin", "BEN", "204",
					"Republic of Benin" },
			new String[] { "BM", NORTH_AMERICA, "Bermuda", "BMU", "060",
					"Bermuda" },
			new String[] { "BT", ASIA, "Bhutan", "BTN", "064",
					"Kingdom of Bhutan" },
			new String[] { "BO", SOUTH_AMERICA, "Bolivia", "BOL", "068",
					"Plurinational State of Bolivia" },
			new String[] { "BQ", NORTH_AMERICA,
					"Bonaire, Sint Eustatius and Saba", "BES", "535",
					"Bonaire, Sint Eustatius and Saba" },
			new String[] { "BA", EUROPE, "Bosnia and Herzegovina", "BIH",
					"070", "Bosnia and Herzegovina" },
			new String[] { "BW", AFRICA, "Botswana", "BWA", "072",
					"Republic of Botswana" },
			new String[] { "BV", ANTARCTICA,
					"Bouvet Island new String[] {Bouvetoya}", "BVT", "074",
					"Bouvet Island new String[] {Bouvetoya}" },
			new String[] { "BR", SOUTH_AMERICA, "Brazil", "BRA", "076",
					"Federative Republic of Brazil" },
			new String[] {
					"IO",
					ASIA,
					"British Indian Ocean Territory new String[] {Chagos Archipelago}",
					"IOT", "086",
					"British Indian Ocean Territory new String[] {Chagos Archipelago}" },
			new String[] { "VG", NORTH_AMERICA, "British Virgin Islands",
					"VGB", "092", "British Virgin Islands" },
			new String[] { "BN", ASIA, "Brunei Darussalam", "BRN", "096",
					"Brunei Darussalam" },
			new String[] { "BG", EUROPE, "Bulgaria", "BGR", "100",
					"Republic of Bulgaria" },
			new String[] { "BF", AFRICA, "Burkina Faso", "BFA", "854",
					"Burkina Faso" },
			new String[] { "BI", AFRICA, "Burundi", "BDI", "108",
					"Republic of Burundi" },
			new String[] { "KH", ASIA, "Cambodia", "KHM", "116",
					"Kingdom of Cambodia" },
			new String[] { "CM", AFRICA, "Cameroon", "CMR", "120",
					"Republic of Cameroon" },
			new String[] { "CA", NORTH_AMERICA, "Canada", "CAN", "124",
					"Canada" },
			new String[] { "CV", AFRICA, "Cape Verde", "CPV", "132",
					"Republic of Cape Verde" },
			new String[] { "KY", NORTH_AMERICA, "Cayman Islands", "CYM", "136",
					"Cayman Islands" },
			new String[] { "CF", AFRICA, "Central African Republic", "CAF",
					"140", "Central African Republic" },
			new String[] { "TD", AFRICA, "Chad", "TCD", "148",
					"Republic of Chad" },
			new String[] { "CL", SOUTH_AMERICA, "Chile", "CHL", "152",
					"Republic of Chile" },
			new String[] { "CN", ASIA, "China", "CHN", "156",
					"People's Republic of China" },
			new String[] { "CX", ASIA, "Christmas Island", "CXR", "162",
					"Christmas Island" },
			new String[] { "CC", ASIA, "Cocos new String[] {Keeling} Islands",
					"CCK", "166", "Cocos new String[] {Keeling} Islands" },
			new String[] { "CO", SOUTH_AMERICA, "Colombia", "COL", "170",
					"Republic of Colombia" },
			new String[] { "KM", AFRICA, "Comoros", "COM", "174",
					"Union of the Comoros" },
			new String[] { "CD", AFRICA, "Congo", "COD", "180",
					"Democratic Republic of the Congo" },
			new String[] { "CG", AFRICA, "Congo", "COG", "178",
					"Republic of the Congo" },
			new String[] { "CK", OCEANIA, "Cook Islands", "COK", "184",
					"Cook Islands" },
			new String[] { "CR", NORTH_AMERICA, "Costa Rica", "CRI", "188",
					"Republic of Costa Rica" },
			new String[] { "CI", AFRICA, "Cote d'Ivoire", "CIV", "384",
					"Republic of Cote d'Ivoire" },
			new String[] { "HR", EUROPE, "Croatia", "HRV", "191",
					"Republic of Croatia" },
			new String[] { "CU", NORTH_AMERICA, "Cuba", "CUB", "192",
					"Republic of Cuba" },
			new String[] { "CW", NORTH_AMERICA, "Curaçao", "CUW", "531",
					"Curaçao" },
			new String[] { "CY", ASIA, "Cyprus", "CYP", "196",
					"Republic of Cyprus" },
			new String[] { "CZ", EUROPE, "Czech Republic", "CZE", "203",
					"Czech Republic" },
			new String[] { "DK", EUROPE, "Denmark", "DNK", "208",
					"Kingdom of Denmark" },
			new String[] { "DJ", AFRICA, "Djibouti", "DJI", "262",
					"Republic of Djibouti" },
			new String[] { "DM", NORTH_AMERICA, "Dominica", "DMA", "212",
					"Commonwealth of Dominica" },
			new String[] { "DO", NORTH_AMERICA, "Dominican Republic", "DOM",
					"214", "Dominican Republic" },
			new String[] { "EC", SOUTH_AMERICA, "Ecuador", "ECU", "218",
					"Republic of Ecuador" },
			new String[] { "EG", AFRICA, "Egypt", "EGY", "818",
					"Arab Republic of Egypt" },
			new String[] { "SV", NORTH_AMERICA, "El Salvador", "SLV", "222",
					"Republic of El Salvador" },
			new String[] { "GQ", AFRICA, "Equatorial Guinea", "GNQ", "226",
					"Republic of Equatorial Guinea" },
			new String[] { "ER", AFRICA, "Eritrea", "ERI", "232",
					"State of Eritrea" },
			new String[] { "EE", EUROPE, "Estonia", "EST", "233",
					"Republic of Estonia" },
			new String[] { "ET", AFRICA, "Ethiopia", "ETH", "231",
					"Federal Democratic Republic of Ethiopia" },
			new String[] { "FO", EUROPE, "Faroe Islands", "FRO", "234",
					"Faroe Islands" },
			new String[] { "FK", SOUTH_AMERICA,
					"Falkland Islands new String[] {Malvinas}", "FLK", "238",
					"Falkland Islands new String[] {Malvinas}" },
			new String[] { "FJ", OCEANIA, "Fiji", "FJI", "242",
					"Republic of Fiji" },
			new String[] { "FI", EUROPE, "Finland", "FIN", "246",
					"Republic of Finland" },
			new String[] { "FR", EUROPE, "France", "FRA", "250",
					"French Republic" },
			new String[] { "GF", SOUTH_AMERICA, "French Guiana", "GUF", "254",
					"French Guiana" },
			new String[] { "PF", OCEANIA, "French Polynesia", "PYF", "258",
					"French Polynesia" },
			new String[] { "TF", ANTARCTICA, "French Southern Territories",
					"ATF", "260", "French Southern Territories" },
			new String[] { "GA", AFRICA, "Gabon", "GAB", "266",
					"Gabonese Republic" },
			new String[] { "GM", AFRICA, "Gambia", "GMB", "270",
					"Republic of the Gambia" },
			new String[] { "GE", ASIA, "Georgia", "GEO", "268", "Georgia" },
			new String[] { "DE", EUROPE, "Germany", "DEU", "276",
					"Federal Republic of Germany" },
			new String[] { "GH", AFRICA, "Ghana", "GHA", "288",
					"Republic of Ghana" },
			new String[] { "GI", EUROPE, "Gibraltar", "GIB", "292", "Gibraltar" },
			new String[] { "GR", EUROPE, "Greece", "GRC", "300",
					"Hellenic Republic Greece" },
			new String[] { "GL", NORTH_AMERICA, "Greenland", "GRL", "304",
					"Greenland" },
			new String[] { "GD", NORTH_AMERICA, "Grenada", "GRD", "308",
					"Grenada" },
			new String[] { "GP", NORTH_AMERICA, "Guadeloupe", "GLP", "312",
					"Guadeloupe" },
			new String[] { "GU", OCEANIA, "Guam", "GUM", "316", "Guam" },
			new String[] { "GT", NORTH_AMERICA, "Guatemala", "GTM", "320",
					"Republic of Guatemala" },
			new String[] { "GG", EUROPE, "Guernsey", "GGY", "831",
					"Bailiwick of Guernsey" },
			new String[] { "GN", AFRICA, "Guinea", "GIN", "324",
					"Republic of Guinea" },
			new String[] { "GW", AFRICA, "Guinea-Bissau", "GNB", "624",
					"Republic of Guinea-Bissau" },
			new String[] { "GY", SOUTH_AMERICA, "Guyana", "GUY", "328",
					"Co-operative Republic of Guyana" },
			new String[] { "HT", NORTH_AMERICA, "Haiti", "HTI", "332",
					"Republic of Haiti" },
			new String[] { "HM", ANTARCTICA,
					"Heard Island and McDonald Islands", "HMD", "334",
					"Heard Island and McDonald Islands" },
			new String[] { "VA", EUROPE,
					"Holy See new String[] {Vatican City State}", "VAT", "336",
					"Holy See new String[] {Vatican City State}" },
			new String[] { "HN", NORTH_AMERICA, "Honduras", "HND", "340",
					"Republic of Honduras" },
			new String[] { "HK", ASIA, "Hong Kong", "HKG", "344",
					"Hong Kong Special Administrative Region of China" },
			new String[] { "HU", EUROPE, "Hungary", "HUN", "348", "Hungary" },
			new String[] { "IS", EUROPE, "Iceland", "ISL", "352",
					"Republic of Iceland" },
			new String[] { "IN", ASIA, "India", "IND", "356",
					"Republic of India" },
			new String[] { "ID", ASIA, "Indonesia", "IDN", "360",
					"Republic of Indonesia" },
			new String[] { "IR", ASIA, "Iran", "IRN", "364",
					"Islamic Republic of Iran" },
			new String[] { "IQ", ASIA, "Iraq", "IRQ", "368", "Republic of Iraq" },
			new String[] { "IE", EUROPE, "Ireland", "IRL", "372", "Ireland" },
			new String[] { "IM", EUROPE, "Isle of Man", "IMN", "833",
					"Isle of Man" },
			new String[] { "IL", ASIA, "Israel", "ISR", "376",
					"State of Israel" },
			new String[] { "IT", EUROPE, "Italy", "ITA", "380",
					"Italian Republic" },
			new String[] { "JM", NORTH_AMERICA, "Jamaica", "JAM", "388",
					"Jamaica" },
			new String[] { "JP", ASIA, "Japan", "JPN", "392", "Japan" },
			new String[] { "JE", EUROPE, "Jersey", "JEY", "832",
					"Bailiwick of Jersey" },
			new String[] { "JO", ASIA, "Jordan", "JOR", "400",
					"Hashemite Kingdom of Jordan" },
			new String[] { "KZ", ASIA, "Kazakhstan", "KAZ", "398",
					"Republic of Kazakhstan" },
			new String[] { "KE", AFRICA, "Kenya", "KEN", "404",
					"Republic of Kenya" },
			new String[] { "KI", OCEANIA, "Kiribati", "KIR", "296",
					"Republic of Kiribati" },
			new String[] { "KP", ASIA, "Korea", "PRK", "408",
					"Democratic People's Republic of Korea" },
			new String[] { "KR", ASIA, "Korea", "KOR", "410",
					"Republic of Korea" },
			new String[] { "KW", ASIA, "Kuwait", "KWT", "414",
					"State of Kuwait" },
			new String[] { "KG", ASIA, "Kyrgyz Republic", "KGZ", "417",
					"Kyrgyz Republic" },
			new String[] { "LA", ASIA, "Lao People's Democratic Republic",
					"LAO", "418", "Lao People's Democratic Republic" },
			new String[] { "LV", EUROPE, "Latvia", "LVA", "428",
					"Republic of Latvia" },
			new String[] { "LB", ASIA, "Lebanon", "LBN", "422",
					"Lebanese Republic" },
			new String[] { "LS", AFRICA, "Lesotho", "LSO", "426",
					"Kingdom of Lesotho" },
			new String[] { "LR", AFRICA, "Liberia", "LBR", "430",
					"Republic of Liberia" },
			new String[] { "LY", AFRICA, "Libya", "LBY", "434", "Libya" },
			new String[] { "LI", EUROPE, "Liechtenstein", "LIE", "438",
					"Principality of Liechtenstein" },
			new String[] { "LT", EUROPE, "Lithuania", "LTU", "440",
					"Republic of Lithuania" },
			new String[] { "LU", EUROPE, "Luxembourg", "LUX", "442",
					"Grand Duchy of Luxembourg" },
			new String[] { "MO", ASIA, "Macao", "MAC", "446",
					"Macao Special Administrative Region of China" },
			new String[] { "MK", EUROPE, "Macedonia", "MKD", "807",
					"Republic of Macedonia" },
			new String[] { "MG", AFRICA, "Madagascar", "MDG", "450",
					"Republic of Madagascar" },
			new String[] { "MW", AFRICA, "Malawi", "MWI", "454",
					"Republic of Malawi" },
			new String[] { "MY", ASIA, "Malaysia", "MYS", "458", "Malaysia" },
			new String[] { "MV", ASIA, "Maldives", "MDV", "462",
					"Republic of Maldives" },
			new String[] { "ML", AFRICA, "Mali", "MLI", "466",
					"Republic of Mali" },
			new String[] { "MT", EUROPE, "Malta", "MLT", "470",
					"Republic of Malta" },
			new String[] { "MH", OCEANIA, "Marshall Islands", "MHL", "584",
					"Republic of the Marshall Islands" },
			new String[] { "MQ", NORTH_AMERICA, "Martinique", "MTQ", "474",
					"Martinique" },
			new String[] { "MR", AFRICA, "Mauritania", "MRT", "478",
					"Islamic Republic of Mauritania" },
			new String[] { "MU", AFRICA, "Mauritius", "MUS", "480",
					"Republic of Mauritius" },
			new String[] { "YT", AFRICA, "Mayotte", "MYT", "175", "Mayotte" },
			new String[] { "MX", NORTH_AMERICA, "Mexico", "MEX", "484",
					"United Mexican States" },
			new String[] { "FM", OCEANIA, "Micronesia", "FSM", "583",
					"Federated States of Micronesia" },
			new String[] { "MD", EUROPE, "Moldova", "MDA", "498",
					"Republic of Moldova" },
			new String[] { "MC", EUROPE, "Monaco", "MCO", "492",
					"Principality of Monaco" },
			new String[] { "MN", ASIA, "Mongolia", "MNG", "496", "Mongolia" },
			new String[] { "ME", EUROPE, "Montenegro", "MNE", "499",
					"Montenegro" },
			new String[] { "MS", NORTH_AMERICA, "Montserrat", "MSR", "500",
					"Montserrat" },
			new String[] { "MA", AFRICA, "Morocco", "MAR", "504",
					"Kingdom of Morocco" },
			new String[] { "MZ", AFRICA, "Mozambique", "MOZ", "508",
					"Republic of Mozambique" },
			new String[] { "MM", ASIA, "Myanmar", "MMR", "104",
					"Republic of the Union of Myanmar" },
			new String[] { NORTH_AMERICA, AFRICA, "Namibia", "NAM", "516",
					"Republic of Namibia" },
			new String[] { "NR", OCEANIA, "Nauru", "NRU", "520",
					"Republic of Nauru" },
			new String[] { "NP", ASIA, "Nepal", "NPL", "524",
					"Federal Democratic Republic of Nepal" },
			new String[] { "NL", EUROPE, "Netherlands", "NLD", "528",
					"Kingdom of the Netherlands" },
			new String[] { "NC", OCEANIA, "New Caledonia", "NCL", "540",
					"New Caledonia" },
			new String[] { "NZ", OCEANIA, "New Zealand", "NZL", "554",
					"New Zealand" },
			new String[] { "NI", NORTH_AMERICA, "Nicaragua", "NIC", "558",
					"Republic of Nicaragua" },
			new String[] { "NE", AFRICA, "Niger", "NER", "562",
					"Republic of Niger" },
			new String[] { "NG", AFRICA, "Nigeria", "NGA", "566",
					"Federal Republic of Nigeria" },
			new String[] { "NU", OCEANIA, "Niue", "NIU", "570", "Niue" },
			new String[] { "NF", OCEANIA, "Norfolk Island", "NFK", "574",
					"Norfolk Island" },
			new String[] { "MP", OCEANIA, "Northern Mariana Islands", "MNP",
					"580", "Commonwealth of the Northern Mariana Islands" },
			new String[] { "NO", EUROPE, "Norway", "NOR", "578",
					"Kingdom of Norway" },
			new String[] { "OM", ASIA, "Oman", "OMN", "512",
					"Sultanate of Oman" },
			new String[] { "PK", ASIA, "Pakistan", "PAK", "586",
					"Islamic Republic of Pakistan" },
			new String[] { "PW", OCEANIA, "Palau", "PLW", "585",
					"Republic of Palau" },
			new String[] { "PS", ASIA, "Palestinian Territory", "PSE", "275",
					"Occupied Palestinian Territory" },
			new String[] { "PA", NORTH_AMERICA, "Panama", "PAN", "591",
					"Republic of Panama" },
			new String[] { "PG", OCEANIA, "Papua New Guinea", "PNG", "598",
					"Independent State of Papua New Guinea" },
			new String[] { "PY", SOUTH_AMERICA, "Paraguay", "PRY", "600",
					"Republic of Paraguay" },
			new String[] { "PE", SOUTH_AMERICA, "Peru", "PER", "604",
					"Republic of Peru" },
			new String[] { "PH", ASIA, "Philippines", "PHL", "608",
					"Republic of the Philippines" },
			new String[] { "PN", OCEANIA, "Pitcairn Islands", "PCN", "612",
					"Pitcairn Islands" },
			new String[] { "PL", EUROPE, "Poland", "POL", "616",
					"Republic of Poland" },
			new String[] { "PT", EUROPE, "Portugal", "PRT", "620",
					"Portuguese Republic" },
			new String[] { "PR", NORTH_AMERICA, "Puerto Rico", "PRI", "630",
					"Commonwealth of Puerto Rico" },
			new String[] { "QA", ASIA, "Qatar", "QAT", "634", "State of Qatar" },
			new String[] { "RE", AFRICA, "Réunion", "REU", "638", "Réunion" },
			new String[] { "RO", EUROPE, "Romania", "ROU", "642", "Romania" },
			new String[] { "RU", EUROPE, "Russian Federation", "RUS", "643",
					"Russian Federation" },
			new String[] { "RW", AFRICA, "Rwanda", "RWA", "646",
					"Republic of Rwanda" },
			new String[] { "BL", NORTH_AMERICA, "Saint Barthélemy", "BLM",
					"652", "Saint Barthélemy" },
			new String[] { "SH", AFRICA,
					"Saint Helena, Ascension and Tristan da Cunha", "SHN",
					"654", "Saint Helena, Ascension and Tristan da Cunha" },
			new String[] { "KN", NORTH_AMERICA, "Saint Kitts and Nevis", "KNA",
					"659", "Federation of Saint Kitts and Nevis" },
			new String[] { "LC", NORTH_AMERICA, "Saint Lucia", "LCA", "662",
					"Saint Lucia" },
			new String[] { "MF", NORTH_AMERICA, "Saint Martin", "MAF", "663",
					"Saint Martin new String[] {French part}" },
			new String[] { "PM", NORTH_AMERICA, "Saint Pierre and Miquelon",
					"SPM", "666", "Saint Pierre and Miquelon" },
			new String[] { "VC", NORTH_AMERICA,
					"Saint Vincent and the Grenadines", "VCT", "670",
					"Saint Vincent and the Grenadines" },
			new String[] { "WS", OCEANIA, "Samoa", "WSM", "882",
					"Independent State of Samoa" },
			new String[] { "SM", EUROPE, "San Marino", "SMR", "674",
					"Republic of San Marino" },
			new String[] { "ST", AFRICA, "Sao Tome and Principe", "STP", "678",
					"Democratic Republic of Sao Tome and Principe" },
			new String[] { SOUTH_AMERICA, ASIA, "Saudi Arabia", "SAU", "682",
					"Kingdom of Saudi Arabia" },
			new String[] { "SN", AFRICA, "Senegal", "SEN", "686",
					"Republic of Senegal" },
			new String[] { "RS", EUROPE, "Serbia", "SRB", "688",
					"Republic of Serbia" },
			new String[] { "SC", AFRICA, "Seychelles", "SYC", "690",
					"Republic of Seychelles" },
			new String[] { "SL", AFRICA, "Sierra Leone", "SLE", "694",
					"Republic of Sierra Leone" },
			new String[] { "SG", ASIA, "Singapore", "SGP", "702",
					"Republic of Singapore" },
			new String[] { "SX", NORTH_AMERICA,
					"Sint Maarten new String[] {Dutch part}", "SXM", "534",
					"Sint Maarten new String[] {Dutch part}" },
			new String[] { "SK", EUROPE,
					"Slovakia new String[] {Slovak Republic}", "SVK", "703",
					"Slovakia new String[] {Slovak Republic}" },
			new String[] { "SI", EUROPE, "Slovenia", "SVN", "705",
					"Republic of Slovenia" },
			new String[] { "SB", OCEANIA, "Solomon Islands", "SLB", "090",
					"Solomon Islands" },
			new String[] { "SO", AFRICA, "Somalia", "SOM", "706",
					"Somali Republic" },
			new String[] { "ZA", AFRICA, "South Africa", "ZAF", "710",
					"Republic of South Africa" },
			new String[] { "GS", ANTARCTICA,
					"South Georgia and the South Sandwich Islands", "SGS",
					"239", "South Georgia and the South Sandwich Islands" },
			new String[] { "SS", AFRICA, "South Sudan", "SSD", "728",
					"Republic of South Sudan" },
			new String[] { "ES", EUROPE, "Spain", "ESP", "724",
					"Kingdom of Spain" },
			new String[] { "LK", ASIA, "Sri Lanka", "LKA", "144",
					"Democratic Socialist Republic of Sri Lanka" },
			new String[] { "SD", AFRICA, "Sudan", "SDN", "729",
					"Republic of Sudan" },
			new String[] { "SR", SOUTH_AMERICA, "Suriname", "SUR", "740",
					"Republic of Suriname" },
			new String[] { "SJ", EUROPE, "Svalbard & Jan Mayen Islands", "SJM",
					"744", "Svalbard & Jan Mayen Islands" },
			new String[] { "SZ", AFRICA, "Swaziland", "SWZ", "748",
					"Kingdom of Swaziland" },
			new String[] { "SE", EUROPE, "Sweden", "SWE", "752",
					"Kingdom of Sweden" },
			new String[] { "CH", EUROPE, "Switzerland", "CHE", "756",
					"Swiss Confederation" },
			new String[] { "SY", ASIA, "Syrian Arab Republic", "SYR", "760",
					"Syrian Arab Republic" },
			new String[] { "TW", ASIA, "Taiwan", "TWN", "158",
					"Taiwan, Province of China" },
			new String[] { "TJ", ASIA, "Tajikistan", "TJK", "762",
					"Republic of Tajikistan" },
			new String[] { "TZ", AFRICA, "Tanzania", "TZA", "834",
					"United Republic of Tanzania" },
			new String[] { "TH", ASIA, "Thailand", "THA", "764",
					"Kingdom of Thailand" },
			new String[] { "TL", ASIA, "Timor-Leste", "TLS", "626",
					"Democratic Republic of Timor-Leste" },
			new String[] { "TG", AFRICA, "Togo", "TGO", "768",
					"Togolese Republic" },
			new String[] { "TK", OCEANIA, "Tokelau", "TKL", "772", "Tokelau" },
			new String[] { "TO", OCEANIA, "Tonga", "TON", "776",
					"Kingdom of Tonga" },
			new String[] { "TT", NORTH_AMERICA, "Trinidad and Tobago", "TTO",
					"780", "Republic of Trinidad and Tobago" },
			new String[] { "TN", AFRICA, "Tunisia", "TUN", "788",
					"Tunisian Republic" },
			new String[] { "TR", ASIA, "Turkey", "TUR", "792",
					"Republic of Turkey" },
			new String[] { "TM", ASIA, "Turkmenistan", "TKM", "795",
					"Turkmenistan" },
			new String[] { "TC", NORTH_AMERICA, "Turks and Caicos Islands",
					"TCA", "796", "Turks and Caicos Islands" },
			new String[] { "TV", OCEANIA, "Tuvalu", "TUV", "798", "Tuvalu" },
			new String[] { "UG", AFRICA, "Uganda", "UGA", "800",
					"Republic of Uganda" },
			new String[] { "UA", EUROPE, "Ukraine", "UKR", "804", "Ukraine" },
			new String[] { "AE", ASIA, "United Arab Emirates", "ARE", "784",
					"United Arab Emirates" },
			new String[] { "GB", EUROPE,
					"United Kingdom of Great Britain & Northern Ireland",
					"GBR", "826",
					"United Kingdom of Great Britain & Northern Ireland" },
			new String[] { "US", NORTH_AMERICA, "United States of America",
					"USA", "840", "United States of America" },
			new String[] { "UM", OCEANIA,
					"United States Minor Outlying Islands", "UMI", "581",
					"United States Minor Outlying Islands" },
			new String[] { "VI", NORTH_AMERICA, "United States Virgin Islands",
					"VIR", "850", "United States Virgin Islands" },
			new String[] { "UY", SOUTH_AMERICA, "Uruguay", "URY", "858",
					"Eastern Republic of Uruguay" },
			new String[] { "UZ", ASIA, "Uzbekistan", "UZB", "860",
					"Republic of Uzbekistan" },
			new String[] { "VU", OCEANIA, "Vanuatu", "VUT", "548",
					"Republic of Vanuatu" },
			new String[] { "VE", SOUTH_AMERICA, "Venezuela", "VEN", "862",
					"Bolivarian Republic of Venezuela" },
			new String[] { "VN", ASIA, "Vietnam", "VNM", "704",
					"Socialist Republic of Vietnam" },
			new String[] { "WF", OCEANIA, "Wallis and Futuna", "WLF", "876",
					"Wallis and Futuna" },
			new String[] { "EH", AFRICA, "Western Sahara", "ESH", "732",
					"Western Sahara" },
			new String[] { "YE", ASIA, "Yemen", "YEM", "887", "Yemen" },
			new String[] { "ZM", AFRICA, "Zambia", "ZMB", "894",
					"Republic of Zambia" },
			new String[] { "ZW", AFRICA, "Zimbabwe", "ZWE", "716",
					"Republic of Zimbabwe" } };
	public static final Map<String, String> countryToContinent = new HashMap<String, String>(
			COUNTRIES.length * 9 / 2);
	public static final Map<String, String> iso2Toiso3 = new HashMap<String, String>(
			COUNTRIES.length * 3 / 2);
	public static final Map<String, String> countryNameToIsoCode = new HashMap<String, String>(
			COUNTRIES.length * 3);
	public static Map<String, String> worldRegionToContinent = new HashMap<String, String>(
			21);

	public static String[] continentNames = new String[7];

	static {
		for (String[] entry : COUNTRIES) {
			countryToContinent.put(entry[0], entry[1]);
			countryToContinent.put(entry[3], entry[1]);
			countryToContinent.put(entry[4], entry[1]);
			iso2Toiso3.put(entry[0], entry[3]);
			countryNameToIsoCode.put(entry[2], entry[3]);
			countryNameToIsoCode.put(entry[5], entry[3]);
		}
		worldRegionToContinent.put("Africa", AFRICA);
		worldRegionToContinent.put("Antartica", ANTARCTICA);
		worldRegionToContinent.put("Asia", ASIA);
		worldRegionToContinent.put("Europe", EUROPE);
		worldRegionToContinent.put("North America", NORTH_AMERICA);
		worldRegionToContinent.put("Oceania", OCEANIA);
		worldRegionToContinent.put("South America", SOUTH_AMERICA);
		worldRegionToContinent.put(
				continentNames[0] = GeoMessages.getString(GeoMessages.PREFIX
						+ AFRICA), AFRICA);
		worldRegionToContinent.put(
				continentNames[1] = GeoMessages.getString(GeoMessages.PREFIX
						+ ANTARCTICA), ANTARCTICA);
		worldRegionToContinent.put(
				continentNames[2] = GeoMessages.getString(GeoMessages.PREFIX
						+ ASIA), ASIA);
		worldRegionToContinent.put(
				continentNames[3] = GeoMessages.getString(GeoMessages.PREFIX
						+ EUROPE), EUROPE);
		worldRegionToContinent.put(
				continentNames[4] = GeoMessages.getString(GeoMessages.PREFIX
						+ NORTH_AMERICA), NORTH_AMERICA);
		worldRegionToContinent.put(
				continentNames[5] = GeoMessages.getString(GeoMessages.PREFIX
						+ OCEANIA), OCEANIA);
		worldRegionToContinent.put(
				continentNames[6] = GeoMessages.getString(GeoMessages.PREFIX
						+ SOUTH_AMERICA), SOUTH_AMERICA);
	}

	private LocationConstants() {
		// Do not instantiate
	}

}
